from enum import Enum
from typing import Any, Dict, List
from pydantic import BaseModel, Field
from app.schemas.pedagogy import PedagogyDecision


class LessonBlockType(str, Enum):
    OBJECTIVE = "objective"
    EXPLANATION = "explanation"
    WORKED_EXAMPLE = "worked_example"
    VISUAL_SPEC = "visual_spec"
    PRACTICE_TASK = "practice_task"


class LessonBlock(BaseModel):
    """A structured learning unit consumed by UniOS LessonRenderer (NO raw UI code)."""

    type: LessonBlockType
    title: str
    content: str
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Structured instructions for renderers (e.g. animation steps, diagram data, practice hints)",
    )


class GeneratedLesson(BaseModel):
    """The final structured lesson generated by AI/ML-2."""

    context_id: str
    topic: str
    pedagogy_decision: PedagogyDecision
    blocks: List[LessonBlock] = Field(
        ..., min_length=1, description="Ordered sequence of structured learning blocks"
    )
