from enum import Enum
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field
from app.schemas.pedagogy import PedagogyDecision


class LessonBlockType(str, Enum):
    # Sprint 1-3 types (preserved for 100% backward compatibility)
    OBJECTIVE = "objective"
    EXPLANATION = "explanation"
    WORKED_EXAMPLE = "worked_example"
    VISUAL_SPEC = "visual_spec"
    PRACTICE_TASK = "practice_task"

    # Canonical Universal Learning Blocks (Engineering Bible Section 7.4 / 13.4)
    TEXT = "text"
    EXAMPLE = "example"
    DIAGRAM = "diagram"
    INTERACTIVE_QUESTION = "interactive_question"
    PRACTICE = "practice"
    ASSESSMENT = "assessment"
    CODE = "code"
    SIMULATION = "simulation"
    VIDEO = "video"
    VOICE = "voice"


class LessonBlock(BaseModel):
    """A structured learning unit consumed by UniOS LessonRenderer (NO raw UI code)."""

    type: LessonBlockType
    title: Optional[str] = Field(default="", description="Block title or header")
    content: Union[str, Dict[str, Any]] = Field(
        ...,
        description="Structured content body (markdown prose or structured dictionary, never raw UI/JSX code)",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Structured instructions for renderers (e.g. animation steps, diagram data, practice hints)",
    )


class AssessmentIntent(BaseModel):
    """Pedagogical assessment intent generated with the lesson (A2-S4-02)."""

    target_concepts: List[str] = Field(default_factory=list)
    assessment_mode: str = Field(
        default="formative",
        description="Assessment mode: formative | diagnostic | summative | viva",
    )
    difficulty: str = Field(default="beginner")
    question_count: int = Field(default=3)
    evaluation_criteria: List[str] = Field(default_factory=list)


class NextLearningAction(BaseModel):
    """Actionable next step recommended by AI/ML-2 based on pedagogy and evidence (A2-S4-04)."""

    action_type: str = Field(
        ...,
        description="Action type: reassessment | practice | next_topic | build_artifact | review",
    )
    target_topic: str
    rationale: str
    urgency: str = Field(default="normal", description="normal | immediate | deferred")


class GeneratedLesson(BaseModel):
    """The final structured lesson generated by AI/ML-2 (A2-S4-02)."""

    context_id: str
    request_id: Optional[str] = Field(
        default=None,
        description="Cross-service tracing identifier aligned with universal Engineering Bible",
    )
    topic: str
    pedagogy_decision: PedagogyDecision
    blocks: List[LessonBlock] = Field(
        ..., min_length=1, description="Ordered sequence of structured learning blocks"
    )
    prerequisites: List[str] = Field(
        default_factory=list,
        description="Prerequisite concepts or knowledge needed for this lesson",
    )
    assessment_intent: Optional[AssessmentIntent] = Field(
        default=None,
        description="Assessment intent for downstream evaluation and mastery loop",
    )
    next_action: Optional[NextLearningAction] = Field(
        default=None,
        description="Actionable next step recommended by AI/ML-2",
    )

    def model_post_init(self, __context):
        if self.request_id is None and self.context_id:
            self.request_id = self.context_id
        elif self.context_id is None and self.request_id:
            self.context_id = self.request_id

